packages:
  - packages/*
  - demos/*

# クールダウンの設定(7日)
minimumReleaseAge: 10080 # 7日（分単位）

catalogMode: strict

catalog:
  "@changesets/cli": 3.0.2
  "@types/node": ^26

  "@tiptap/extension-image": ^3.31.0
  "@tiptap/extension-table": ^3.31.0
  "@tiptap/core": ^3.31.0
  "@tiptap/pm": ^3.31.0
  "@tiptap/starter-kit": "^3.31.0"
  "@tiptap/vue-3": "^3.31.0"

  happy-dom: ^20.14.5

  typescript: 6.0.3
  vite: npm:@voidzero-dev/vite-plus-core@1.0.0
  vite-plus: 1.0.0
  vue-tsc: ^3.0.8

  #demo's dependencies
  "@tailwindcss/vite": "^4.3.3"
  "@vitejs/plugin-vue": "^6.0.9"
  "tailwindcss": ^4.3.3
  vue: ^3.5.43

overrides:
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
